name: "添加 React 组件"
description: "添加一个 React 组件"
title: 'Add <React Component Name>'

body:
  - type: markdown
    attributes:
      value: |
        🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧   
        注意：在这里分享组件按照要求提交，自动生成 PR，否则会被关闭。
        🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧   


  - type: input
    attributes:
      label: Github 仓库地址
      description: 提供文档网站地址
      placeholder: ex. https://github.com/uiwjs/react-codemirror
    validations:
      required: true

  - type: textarea
    attributes:
      label: 组件说明项目
      description: 您可以在这里简明扼要的语言描述一下 React 组件。
      placeholder: 描述一下 React 组件
    validations:
      required: true

  - type: input
    attributes:
      label: NPM 包名称
      description: 提供 npm 安装包名称
      placeholder: "@uiw/react-codemirror"
    validations:
      required: true

  - type: dropdown
    validations:
      required: true
    attributes:
      label: 选择一个分类
      options:
        - Table 表格
        - Infinite Scroll 无限滚动
        - Overlay 叠加
        - Notification 通知
        - Tooltip 工具提示
        - Menu 菜单
        - Sticky
        - Tabs 选项卡
        - Loader 加载
        - Carousel
        - Buttons 按钮
        - Collapse
        - Chart 图表
        - Command palette 命令面板
        - Tree 树
        - UI Navigation 用户界面导航
        - Custom Scrollbar 自定义滚动条
        - Audio / Video 音频视频
        - Map 地图
        - Time/Date/Age 时间/日期/年龄
        - Photo/Image 照片/图像
        - Icons 图标
        - Paginator 分页器
        - Markdown 预览
        - Canvas 画布
        - Miscellaneous 各种各样的
