name: "添加 React 组件"
description: "添加一个 React 组件"
title: 'Add <React Component Name>'

body:
  - type: markdown
    attributes:
      value: |
        🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧   
        注意：在这里分享组件按照要求提交，自动生成 PR，否则会被关闭。
        🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧   

