name: "添加 React 组件"
description: "Add React Component"
title: 'Add <React Component Name>'

body:
  - type: markdown
    attributes:
      value: |
        🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧   
        注意：在这里分享组件按照要求提交，自动生成 PR，否则会被关闭。
        🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧   


  - type: input
    attributes:
      label: Github URL
      description: Github URL
      placeholder: ex. https://github.com/uiwjs/react-codemirror
    validations:
      required: true
